#!/bin/bash

# bashrc
source ~/.profile

[ -n "$PS1" ] && source ~/.bash_profile

export NVM_DIR="/Users/aaronpollack/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm use default

PATH="/Users/aaronpollack/perl5/bin${PATH+:}${PATH}"; export PATH;
PERL5LIB="/Users/aaronpollack/perl5/lib/perl5${PERL5LIB+:}${PERL5LIB}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Users/aaronpollack/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/Users/aaronpollack/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/aaronpollack/perl5"; export PERL_MM_OPT;