#!/bin/bash

#===============================================================
#
# ALIASES AND FUNCTIONS
#
#===============================================================

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ...
alias ..="cd .."
alias ...="cd ../.."

# Shortcuts
alias reload='source ~/.bashrc'
alias path='echo -e ${PATH//:/\\n}'

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en4 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# ----------------------------------------------------------------------
# Safeguards
# ----------------------------------------------------------------------

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
# -> Prevents accidentally clobbering files.
alias mkdir='mkdir -p'

# ----------------------------------------------------------------------
# ls less With DIRCOLORS
# ----------------------------------------------------------------------
# ref: http://ss64.com/osx/ls.html

# grc overides for ls
#   Made possible through contributions from generous benefactors like
#   `brew install coreutils`
if $(gls &>/dev/null)
then
  alias ls="gls -F --color"
fi

# List all files colorized in long format
alias ll="ls -alF"
# Long form no user group, color
alias l="ls -oG"
# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

#Git
alias lolprune="git branch --merged | grep -v '\*' | grep -v master | grep -v dev | xargs -n 1 git branch -d"

#Why the fuck do I always forget this???
alias lolserv="lsof -i -n -P | grep LISTEN"
alias lolhost="netstat | grep 'tcp\|udp' | awk '{ print $5; }' | cut -d: -f1 | sort | uniq -c | sort -nr"

alias lolwho="ping `ipconfig getifaddr en4` && arp -a"

alias lollist="tr -s ' ' | cut -d ' ' -f 2 | tr '\n' ',' | sed 's/,$//'" #newline delimted to comma.
alias lolgrep="grep -E -o \"Tra\..{0,9}\""
alias netlei="sudo netstat -tnp|grep ESTABLISHED|awk '{print $5}'|sed 's/::ffff://g'|sed 's/:/ /g'|awk '{print $1}'|sort -n|uniq -c|sort -n -r|more"

alias lolport="ssh -L 5005:50.181.213.215:5005 -N 127.0.0.1"
alias lolinstall="PATH=\"$PATH:/usr/local/bin\" npm install -g gulp"
